/** Shared styles for Team Knock Control desk (Simple + Round Robin). */
export const knockControlStyles = {
  knockSections: { display: "flex", flexDirection: "column", gap: 22 },
  knockSectionBlock: { display: "flex", flexDirection: "column", gap: 8 },
  knockSectionHeadAlive: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: "#5CFF72",
    padding: "0 4px",
  },
  knockSectionHeadElim: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: "#9aa3b0",
    padding: "0 4px",
  },
  knockSectionCount: {
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: 0,
    textTransform: "none",
    color: "#6b8490",
    padding: "2px 8px",
    borderRadius: 999,
    background: "rgba(255,255,255,.05)",
    border: "1px solid rgba(255,255,255,.08)",
  },
  knockSectionEmpty: {
    margin: 0,
    padding: "14px 12px",
    fontSize: 12,
    fontWeight: 600,
    color: "#6b8490",
    fontStyle: "italic",
  },
  knockGrid: { display: "grid", gap: 6 },
  knockGridElim: {
    padding: "8px 0 0",
    borderTop: "1px solid rgba(255,255,255,.06)",
  },
  knockRow: {
    display: "grid",
    gridTemplateColumns: "52px minmax(140px, 200px) 150px minmax(120px, 150px) 1fr",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 12,
    background: "rgba(255,255,255,.02)",
    border: "1px solid rgba(255,255,255,.04)",
  },
  knockTeamNum: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minWidth: 0,
  },
  knockTeamNumLabel: {
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 1,
    color: "#6b8490",
    textTransform: "uppercase",
  },
  knockTeam: { display: "flex", alignItems: "center", gap: 10 },
  aliveBars: { display: "flex", alignItems: "center", gap: 4 },
  aliveBar: { width: 8, height: 28, borderRadius: 2 },
  knockFinishPts: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minWidth: 0,
  },
  knockFinishPtsLabel: {
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 1,
    color: "#6b8490",
    textTransform: "uppercase",
  },
  knockFinishPtsCtl: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 2,
    minWidth: 52,
    padding: "4px 6px",
    borderRadius: 10,
    background: "rgba(0,0,0,.25)",
    border: "1px solid rgba(255,255,255,.08)",
  },
  knockFinishArrowBtn: {
    border: "none",
    margin: 0,
    padding: "2px 0",
    borderRadius: 6,
    background: "rgba(255,255,255,.06)",
    color: "#7ee8ff",
    fontSize: 11,
    fontWeight: 900,
    cursor: "pointer",
    lineHeight: 1,
  },
  knockFinishPtsValue: {
    textAlign: "center",
    fontWeight: 900,
    fontSize: 16,
    color: "#F1CF69",
    lineHeight: 1,
    padding: "2px 0",
    userSelect: "none",
  },
  knockBtns: { display: "flex", flexWrap: "wrap", gap: 6, justifyContent: "flex-end" },
  knockBtn: {
    background: "#122F36",
    color: "#E9FBFD",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#244A53",
    borderRadius: 10,
    padding: "8px 12px",
    fontWeight: 800,
    fontSize: 12,
    cursor: "pointer",
    minWidth: 36,
    textAlign: "center",
  },
  knockBtnDanger: {
    background: "#3A1620",
    color: "#FF6B6B",
    borderColor: "#6B2B3B",
  },
  knockBtnRestore: {
    background: "#12382e",
    color: "#5CFF72",
    borderColor: "#2d6b4a",
  },
  rankBadge: {
    background: "rgba(241,207,105,.15)",
    color: "#F1CF69",
    padding: "4px 10px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 800,
  },
  sourceToggleRow: { display: "flex", flexWrap: "wrap", gap: 8, marginTop: 10 },
  sourceBtn: {
    padding: "8px 14px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,.12)",
    background: "rgba(255,255,255,.04)",
    color: "#e8edf4",
    fontWeight: 800,
    fontSize: 12,
    cursor: "pointer",
  },
  sourceBtnActive: {
    border: "1px solid rgba(230,57,70,.55)",
    background: "rgba(230,57,70,.15)",
    color: "#fff",
  },
  matchBtn: {
    padding: "8px 14px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,.12)",
    background: "rgba(255,255,255,.04)",
    color: "#e8edf4",
    fontWeight: 800,
    fontSize: 12,
    cursor: "pointer",
  },
};
